version: "3.7"

services:
  echoserver:
    image: jmalloc/echo-server:latest
    networks:
      - integrations
    deploy:
      mode: replicated
      replicas: 3

  haproxy:
    image: haproxytech/haproxy-alpine:latest
    ports:
      - 3000:80
      - 8404:8404
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - integrations
    depends_on:
      - echoserver

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.50.0
    command: ["--config=/conf/collector.yml"]
    ports:
      - 8888:8888
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    volumes:
      - ./collector.yml:/conf/collector.yml:rw
    networks:
      - integrations

networks:
  integrations:
