version: "3.7"
services:
    solr:
        container_name: solr
        image: solr
        environment:
            - 'CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false'
            - 'JAVA_OPTS=-Djava.awt.headless=true -XX:+UseG1GC -Dfile.encoding=UTF-8 -Xms256m -Xmx512m'
            - 'ALLOW_EMPTY_PASSWORD=yes'
        ports:
            - 8983:8983
        stop_grace_period: 1s
        volumes:
            - data:/opt/solr/server/solr/otelcores
        entrypoint:
            - docker-entrypoint.sh
            - solr-precreate
            - otelcores
        networks:
            - integrations
    otel-collector:
        container_name: otel-collector
        build: .
        command: ["--config=/conf/collector.yml"]
        environment:
            LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
        networks:
            - integrations
        volumes:
            - ./collector.yml:/conf/collector.yml:rw
networks:
    integrations:
volumes:
      data:
