version: '3.7'
services:
  wildfly:
    build: 
      context: ./wildfly
      args:
        WILDFLY_NAME: wildfly_otel
        CLUSTER_PW: secret_password
    container_name: "wildfly"
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - integrations
    volumes:
      - "./ping/deployments:/opt/jboss/wildfly/standalone/deployments"
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.53.0
    command: ["--config=/conf/collector.yml"]
    environment:
      LS_ACCESS_TOKEN: "${LS_ACCESS_TOKEN}"
    networks:
        - integrations
    volumes:
        - ./collector.yml:/conf/collector.yml:rw
networks:
    integrations:
