version: "3.7"
services:
    hbase:
      image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
      container_name: hbase
      volumes:
        - hbase_data:/hbase-data
        - hbase_zookeeper_data:/zookeeper-data
      ports:
        - 16000:16000
        - 16010:16010
        - 16020:16020
        - 16030:16030
        - 2888:2888
        - 3888:3888
        - 2181:2181
      environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
        HBASE_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=16010 -Dcom.sun.management.jmxremote.rmi.port=16010 -Djava.rmi.server.hostname=hbase -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false "
      env_file:
        - ./hbase-standalone.env     
      stop_grace_period: 1s
      networks:
          - integrations

    namenode:
      image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
      container_name: namenode
      volumes:
        - hadoop_namenode:/hadoop/dfs/name
      environment:
        - CLUSTER_NAME=test
      env_file:
        - ./hadoop.env

    datanode:
      image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
      container_name: datanode
      volumes:
        - hadoop_datanode:/hadoop/dfs/data
      environment:
        SERVICE_PRECONDITION: "namenode:50070"
      env_file:
        - ./hadoop.env

    resourcemanager:
      image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
      container_name: resourcemanager
      environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
      env_file:
        - ./hadoop.env

    nodemanager1:
      image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
      container_name: nodemanager
      environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
      env_file:
        - ./hadoop.env

    historyserver:
      image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
      container_name: historyserver
      volumes:
        - hadoop_historyserver:/hadoop/yarn/timeline
      environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
      env_file:
        - ./hadoop.env
    otel-collector:
      container_name: otel-collector
      build: .
      command: ["--config=/conf/collector.yml"]
      environment:
          LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
      networks:
          - integrations
      volumes:
          - ./collector.yml:/conf/collector.yml:rw
networks:
  integrations:
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hbase_data:
  hbase_zookeeper_data: