version: "3.7"
services:
    hbase:
      image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
      container_name: hbase
      volumes:
        - hbase_data:/hbase-data
        - hbase_zookeeper_data:/zookeeper-data
      ports:
        - 16000:16000
        - 0.0.0.0:16010:16010
        - 16020:16020
        - 16030:16030
        - 2888:2888
        - 3888:3888
        - 2181:2181
      environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
        CATALINA_OPTS: '-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=16010 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false'
        JAVA_OPTS: '-Djava.awt.headless=true -XX:+UseG1GC -Dfile.encoding=UTF-8 -Xms256m -Xmx512m'
      env_file:
        - ./hbase-standalone.env     
      stop_grace_period: 1s
      networks:
          - integrations
    otel-collector:
      container_name: otel-collector
      build: .
      command: ["--config=/conf/collector.yml"]
      environment:
          LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
      networks:
          - integrations
      volumes:
          - ./collector.yml:/conf/collector.yml:rw
networks:
    integrations: